services:
  postgres:
    container_name: postgres
    image: postgres:15.6
    command: postgres -c 'max_connections=1000'
    restart: always
    hostname: "postgres"
    environment:
      - POSTGRES_USER=hatchet-ext
      - POSTGRES_PASSWORD=hatchet-ext
      - POSTGRES_DB=hatchet-ext
    ports:
      - "5435:5432"
    volumes:
      - hatchet_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d hatchet-ext -U hatchet-ext"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5673:5672" # RabbitMQ
      - "15673:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - "hatchet_rabbitmq_data:/var/lib/rabbitmq"
      - "hatchet_rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf" # Configuration file mount
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
  migration:
    container_name: hatchet-ext-migration
    image: ghcr.io/hatchet-dev/hatchet/hatchet-migrate:latest
    command: /hatchet-ext/hatchet-ext-migrate
    environment:
      DATABASE_URL: "postgres://hatchet-ext:hatchet-ext@postgres:5432/hatchet-ext"
    depends_on:
      postgres:
        condition: service_healthy
  setup-config:
    container_name: hatchet-ext-setup-config
    image: ghcr.io/hatchet-dev/hatchet/hatchet-admin:latest
    command: /hatchet-ext/hatchet-ext-admin quickstart --skip certs --generated-config-dir /hatchet-ext/config --overwrite=false
    environment:
      DATABASE_URL: "postgres://hatchet-ext:hatchet-ext@postgres:5432/hatchet-ext"
      SERVER_MSGQUEUE_RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
      SERVER_AUTH_COOKIE_DOMAIN: localhost:8080
      SERVER_AUTH_COOKIE_INSECURE: "t"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
      SERVER_GRPC_BROADCAST_ADDRESS: localhost:7077
      SERVER_DEFAULT_ENGINE_VERSION: "V1"
      SERVER_INTERNAL_CLIENT_INTERNAL_GRPC_BROADCAST_ADDRESS: hatchet-ext-engine:7070
    volumes:
      - hatchet_certs:/hatchet-ext/certs
      - hatchet_config:/hatchet-ext/config
    depends_on:
      migration:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  hatchet-engine:
    container_name: hatchet-ext-engine
    image: ghcr.io/hatchet-dev/hatchet/hatchet-engine:latest
    command: /hatchet-ext/hatchet-ext-engine --config /hatchet-ext/config
    restart: on-failure
    depends_on:
      setup-config:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
    ports:
      - "7077:7070"
    environment:
      DATABASE_URL: "postgres://hatchet-ext:hatchet-ext@postgres:5432/hatchet-ext"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
    volumes:
      - hatchet_certs:/hatchet-ext/certs
      - hatchet_config:/hatchet-ext/config
  hatchet-dashboard:
    container_name: hatchet-ext-dashboard
    image: ghcr.io/hatchet-dev/hatchet/hatchet-dashboard:latest
    command: sh ./entrypoint.sh --config /hatchet-ext/config
    ports:
      - 8080:80
    restart: on-failure
    depends_on:
      setup-config:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "postgres://hatchet-ext:hatchet-ext@postgres:5432/hatchet-ext"
    volumes:
      - hatchet_certs:/hatchet-ext/certs
      - hatchet_config:/hatchet-ext/config
  valkey:
    container_name: valkey
    image: valkey/valkey
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 5s
      retries: 5
    environment:
      VALKEY_EXTRA_FLAGS: --requirepass developer --save 60 1 --loglevel warning
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  hatchet_postgres_data:
  hatchet_rabbitmq_data:
  hatchet_rabbitmq.conf:
  hatchet_config:
  hatchet_certs:
  valkey_data:


